{
    "name": "Real Estate Nacho",
    "version": "1.0",
    "summary": "Real estate management module",
    "description": "Module to manage real estate properties, agents, and clients.",
    "author": "Nacho",
    "category": "Real Estate",
    "depends": ["base", "mail", "contacts"],
    "data": [
        "security/real_estate_security.xml",
        "security/ir.model.access.csv",
        "views/realestate_property_views.xml", 
        "views/realestate_visit_views.xml",
        "views/realestate_offer_views.xml",
        "views/realestate_category_views.xml",
        "views/realestate_property_tag_views.xml",
        "views/realestate_contract_views.xml",
        "views/realestate_agent_views.xml",
        "views/realestate_owner_views.xml",
        "views/realestate_property_image_views.xml",
        "views/realestate_property_incident_views.xml",
        "wizard/realestate_property_change_stage_views.xml",
        "wizard/realestate_property_schedule_visits_views.xml",
        "wizard/realestate_visit_change_state_views.xml",
        "wizard/realestate_partner_wizard_views.xml",
        "report/realestate_property_report.xml",
        "report/realestate_property_simple_report.xml",
        "report/realestate_contract_report.xml",
        "report/realestate_offer_report.xml",
        "views/realestate_menuitems.xml",
        "data/realestate_cron.xml"],
    "installable": True,
    "application": True,
}
