{
    "name": "Real Estate Nacho",
    "version": "1.0",
    "summary": "Real estate management module",
    "description": "Module to manage real estate properties, agents, and clients.",
    "author": "Nacho",
    "category": "Real Estate",
    "depends": ["base"],
    "data": [
        "data/ir_cron.xml",
        "data/ir_sequence.xml",
        "security/real_estate_security.xml",
        "security/ir.model.access.csv",
        "views/realestate_property_views.xml", 
        "views/realestate_visit_views.xml",
        "views/realestate_offer_views.xml",
        "views/realestate_category_views.xml",
        "views/realestate_contract_views.xml",
        "views/realestate_agent_views.xml",
        "views/realestate_owner_views.xml",
        "views/realestate_menuitems.xml",
        "views/realestate_property_tag_views.xml",
        "wizard/realestate_property_change_stage.xml",
        "wizard/realestate_propery_schedule_visits.xml",
        "wizard/realestate_visit_change_state.xml",
        "report/realestate_property_report.xml",
        "report/realestate_property_simple_report.xml",
        "report/realestate_contract_report.xml",
        "report/realestate_offer_report.xml",
    ],
    "installable": True,
    "application": True,
}